inherit_from:
  - .rubocop-shared.yml

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - bin/**/*
    - test/dummy/bin/**/*
    - test/dummy/db/schema.rb

Gemspec/OrderedDependencies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - test/**/*
    - config/routes.rb
    - hackathon_manager.gemspec
